//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Deltas;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Routing.Controllers;
using Microsoft.AspNetCore.OData.Results;
using Northwind.Odata.Api.Infrastructure.Exceptions;
using Northwind.Odata.Api.Infrastructure.Errors;
using Northwind.Odata.Api.Infrastructure.Logging;
using Northwind.Odata.Api.Data;
using Shared.Models;

namespace Northwind.Odata.Api.Controllers
{
    public partial class Entities1Controller : ODataController
    {
        private readonly ILogger<Entities1Controller> _logger;
        private readonly ApplicationErrorHandler _applicationErrorHandler;
        private readonly NorthwindContext _context;
        
        public Entities1Controller(ILogger<Entities1Controller> logger, ApplicationErrorHandler applicationErrorHandler, NorthwindContext context)
        {
            _logger = logger;
            _applicationErrorHandler = applicationErrorHandler;
            _context = context;
        }

        #region Orders

        [EnableQuery]
        [HttpGet("odata/Orders")]
        [HttpGet("odata/Orders/$count")]
        public IActionResult GetOrders()
        {
            return Ok(_context.Orders);
        }

        [EnableQuery]
        [HttpGet("odata/Orders({key})")]
        public IActionResult GetOrders(int key)
        {
            _logger.TraceMethodEntry();

            if (!ModelState.IsValid)
            {
                return _applicationErrorHandler.HandleInvalidModelState(HttpContext, ModelState);
            }

            var entity = _context.Orders.Where(x => x.OrderId == key);

            if (!entity.Any())
            {
                throw new EntityNotFoundException 
                {
                    EntityName = nameof(Order),
                    EntityId = key
                };
            }

            return Ok(SingleResult.Create(entity));
        }

        [HttpPost("odata/Orders")]
        public IActionResult PostOrder([FromBody]Order entity, CancellationToken token)
        {
            _logger.TraceMethodEntry();

            if (!ModelState.IsValid)
            {
                return _applicationErrorHandler.HandleInvalidModelState(HttpContext, ModelState);
            }

            _context.Add(entity);
            _context.SaveChanges();

            return Created(entity);
        }

        [HttpPut("odata/Orders({key})")]
        public IActionResult PutOrder(int key, [FromBody] Order entity)
        {
            _logger.TraceMethodEntry();

            if (!ModelState.IsValid)
            {
                return _applicationErrorHandler.HandleInvalidModelState(HttpContext, ModelState);
            }

            var original = _context.Orders.Find(key);

            if (original == null)
            {
                throw new EntityNotFoundException 
                {
                    EntityName = nameof(Order),
                    EntityId = key
                };
            }

            _context.Entry(original)
                .CurrentValues
                .SetValues(entity);

            _context.SaveChanges();

            return Ok(original);
        }

        [HttpPatch("odata/Orders({key})")]
        public IActionResult PatchOrder(int key, Delta<Order> delta)
        {
            _logger.TraceMethodEntry();

            if (!ModelState.IsValid)
            {
                return _applicationErrorHandler.HandleInvalidModelState(HttpContext, ModelState);
            }

            var original = _context.Orders.Find(key);

            if (original == null)
            {
                throw new EntityNotFoundException
                {
                    EntityName = nameof(Order),
                    EntityId = key
                };
            }

            delta.Patch(original);

            _context.SaveChanges();

            return Updated(original);
        }

        [HttpDelete("odata/Orders({key})")]
        public IActionResult DeleteOrder(int key)
        {
            var original = _context.Orders.Find(key);

            if (original == null)
            {
                throw new EntityNotFoundException
                {
                    EntityName = nameof(Order),
                    EntityId = key
                };
            }

            _context.Orders.Remove(original);
            _context.SaveChanges();
            return Ok();
        }


        #endregion Orders

    }
}

