//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Deltas;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Routing.Controllers;
using Microsoft.AspNetCore.OData.Results;
using Northwind.Odata.Api.Infrastructure.Exceptions;
using Northwind.Odata.Api.Infrastructure.Errors;
using Northwind.Odata.Api.Infrastructure.Logging;
using Northwind.Odata.Api.Data;
using Shared.Models;

namespace Northwind.Odata.Api.Controllers
{

        #region Employee
            public partial class EmployeeController : ODataController
    {
        private readonly ILogger<EmployeeController> _logger;
        private readonly ApplicationErrorHandler _applicationErrorHandler;
        private readonly NorthwindContext _context;
        private readonly IEmployeeRepository _repository;
        public EmployeeController(IEmployeeRepository repository,ILogger<EmployeeController> logger, ApplicationErrorHandler applicationErrorHandler, NorthwindContext context)
        {
            _logger = logger;
            _applicationErrorHandler = applicationErrorHandler;
            _context = context;
            _repository = repository;
        }


        [EnableQuery]
        [HttpGet("odata/Employees")]
        [HttpGet("odata/Employees/$count")]
        public async Task<IActionResult> GetEmployee(CancellationToken cancellationToken)
        {
            var result = await _repository.GetAllAsync(cancellationToken);
            return Ok(result);
        }

        [EnableQuery]
        [HttpGet("odata/Employees({key})")]
        public async Task<IActionResult> GetEmployee(int key, CancellationToken cancellationToken)
        {
            _logger.TraceMethodEntry();

            if (!ModelState.IsValid)
            {
                return _applicationErrorHandler.HandleInvalidModelState(HttpContext, ModelState);
            }
            var entity = await _repository.FindAsync(key, cancellationToken);
            if (entity == null)
            {
                throw new EntityNotFoundException 
                {
                    EntityName = nameof(Employee),
                    EntityId = key
                };
            }

            return Ok(entity);
        }

        [HttpPost("odata/Employees")]
        public async Task<IActionResult> PostEmployee([FromBody]Employee entity, CancellationToken cancellationToken)
        {
            _logger.TraceMethodEntry();

            if (!ModelState.IsValid)
            {
                return _applicationErrorHandler.HandleInvalidModelState(HttpContext, ModelState);
            }

            await _repository.AddAsync(entity, cancellationToken);
            await _repository.SaveChangesAsync(cancellationToken);

            return Created(entity);
        }

        [HttpPut("odata/Employees({key})")]
        public async Task<IActionResult> PutEmployee(int key, [FromBody] Employee entity, CancellationToken cancellationToken)
        {
            _logger.TraceMethodEntry();

            if (!ModelState.IsValid)
            {
                return _applicationErrorHandler.HandleInvalidModelState(HttpContext, ModelState);
            }

            var original = await _repository.FindAsync( key, cancellationToken);
          

            if (original == null)
            {
                throw new EntityNotFoundException 
                {
                    EntityName = nameof(Employee),
                    EntityId = key
                };
            }

            await _repository.UpdateAsync(entity, cancellationToken);
            await _repository.SaveChangesAsync(cancellationToken);

            return Ok(original);
        }

        [HttpPatch("odata/Employees({key})")]
        public async Task <IActionResult> PatchEmployee(int key, Delta<Employee> delta)
        {
            _logger.TraceMethodEntry();

            if (!ModelState.IsValid)
            {
                return _applicationErrorHandler.HandleInvalidModelState(HttpContext, ModelState);
            }

            var original = await _repository.FindAsync( key);

            if (original == null)
            {
                throw new EntityNotFoundException
                {
                    EntityName = nameof(Employee),
                    EntityId = key
                };
            }

            delta.Patch(original);

            _context.SaveChanges();

            return Updated(original);
        }

        [HttpDelete("odata/Employees({key})")]
        public async Task<IActionResult> DeleteEmployee(int key, CancellationToken cancellationToken)
        {
            var original = await _repository.FindAsync(key, cancellationToken);

            if (original == null)
            {
                throw new EntityNotFoundException
                {
                    EntityName = nameof(Employee),
                    EntityId = key
                };
            }

            await _repository.RemoveAsync(original, cancellationToken);
            await _repository.SaveChangesAsync(cancellationToken);
            return Ok();
        }


        [HttpDelete("odata/Employees({int})")]
        public async Task<IActionResult> Delete([FromRoute] int key, CancellationToken cancellationToken)
        {
            var original = await _repository.FindAsync(key, cancellationToken);
            if (original == null)
            {
                return NotFound();
            }
            await _repository.RemoveAsync(original, cancellationToken);
            await _repository.SaveChangesAsync(cancellationToken);
            return Ok();

        #endregion Employee

       }
 }
}

