// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Northwind.Odata.Api.Client.Odata.Categories;
using Northwind.Odata.Api.Client.Odata.Employees;
using Northwind.Odata.Api.Client.Odata.Orders;
using Northwind.Odata.Api.Client.Odata.Products;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Northwind.Odata.Api.Client.Odata
{
    /// <summary>
    /// Builds and executes requests for operations under \odata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OdataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Provides operations to manage the collection of Category entities.</summary>
        public global::Northwind.Odata.Api.Client.Odata.Categories.CategoriesRequestBuilder Categories
        {
            get => new global::Northwind.Odata.Api.Client.Odata.Categories.CategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of Employee entities.</summary>
        public global::Northwind.Odata.Api.Client.Odata.Employees.EmployeesRequestBuilder Employees
        {
            get => new global::Northwind.Odata.Api.Client.Odata.Employees.EmployeesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of Order entities.</summary>
        public global::Northwind.Odata.Api.Client.Odata.Orders.OrdersRequestBuilder Orders
        {
            get => new global::Northwind.Odata.Api.Client.Odata.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the collection of Product entities.</summary>
        public global::Northwind.Odata.Api.Client.Odata.Products.ProductsRequestBuilder Products
        {
            get => new global::Northwind.Odata.Api.Client.Odata.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Northwind.Odata.Api.Client.Odata.OdataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OdataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/odata", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Northwind.Odata.Api.Client.Odata.OdataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OdataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/odata", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
