// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Northwind.Odata.Api.Client.Models.ODataErrors;
using Northwind.Odata.Api.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Northwind.Odata.Api.Client.Odata.Employees.Item.ReportsToNavigation
{
    /// <summary>
    /// Provides operations to manage the reportsToNavigation property of the NorthwindService.Employee entity.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReportsToNavigationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Northwind.Odata.Api.Client.Odata.Employees.Item.ReportsToNavigation.ReportsToNavigationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReportsToNavigationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/odata/Employees/{employeeId}/reportsToNavigation{?%24expand,%24select}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Northwind.Odata.Api.Client.Odata.Employees.Item.ReportsToNavigation.ReportsToNavigationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReportsToNavigationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/odata/Employees/{employeeId}/reportsToNavigation{?%24expand,%24select}", rawUrl)
        {
        }
        /// <summary>
        /// Get reportsToNavigation from Employees
        /// </summary>
        /// <returns>A <see cref="global::Northwind.Odata.Api.Client.Models.Employee"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Northwind.Odata.Api.Client.Models.ODataErrors.ODataError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Northwind.Odata.Api.Client.Models.Employee?> GetAsync(Action<RequestConfiguration<global::Northwind.Odata.Api.Client.Odata.Employees.Item.ReportsToNavigation.ReportsToNavigationRequestBuilder.ReportsToNavigationRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Northwind.Odata.Api.Client.Models.Employee> GetAsync(Action<RequestConfiguration<global::Northwind.Odata.Api.Client.Odata.Employees.Item.ReportsToNavigation.ReportsToNavigationRequestBuilder.ReportsToNavigationRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Northwind.Odata.Api.Client.Models.ODataErrors.ODataError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Northwind.Odata.Api.Client.Models.Employee>(requestInfo, global::Northwind.Odata.Api.Client.Models.Employee.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get reportsToNavigation from Employees
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Northwind.Odata.Api.Client.Odata.Employees.Item.ReportsToNavigation.ReportsToNavigationRequestBuilder.ReportsToNavigationRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Northwind.Odata.Api.Client.Odata.Employees.Item.ReportsToNavigation.ReportsToNavigationRequestBuilder.ReportsToNavigationRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Northwind.Odata.Api.Client.Odata.Employees.Item.ReportsToNavigation.ReportsToNavigationRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Northwind.Odata.Api.Client.Odata.Employees.Item.ReportsToNavigation.ReportsToNavigationRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Northwind.Odata.Api.Client.Odata.Employees.Item.ReportsToNavigation.ReportsToNavigationRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get reportsToNavigation from Employees
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReportsToNavigationRequestBuilderGetQueryParameters 
        {
            /// <summary>Expand related entities</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24expand")]
            public string[]? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("%24expand")]
            public string[] Expand { get; set; }
#endif
            /// <summary>Select properties to be returned</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public string[]? Select { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public string[] Select { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReportsToNavigationRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Northwind.Odata.Api.Client.Odata.Employees.Item.ReportsToNavigation.ReportsToNavigationRequestBuilder.ReportsToNavigationRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
