// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Northwind.Odata.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Employee : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Address { get; set; }
#nullable restore
#else
        public string Address { get; set; }
#endif
        /// <summary>The birthDate property</summary>
        public DateTimeOffset? BirthDate { get; set; }
        /// <summary>The city property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>The country property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>The employeeId property</summary>
        public int? EmployeeId { get; set; }
        /// <summary>The extension property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Extension { get; set; }
#nullable restore
#else
        public string Extension { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The hireDate property</summary>
        public DateTimeOffset? HireDate { get; set; }
        /// <summary>The homePhone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HomePhone { get; set; }
#nullable restore
#else
        public string HomePhone { get; set; }
#endif
        /// <summary>The inverseReportsToNavigation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Northwind.Odata.Api.Client.Models.Employee>? InverseReportsToNavigation { get; set; }
#nullable restore
#else
        public List<global::Northwind.Odata.Api.Client.Models.Employee> InverseReportsToNavigation { get; set; }
#endif
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The notes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The orders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Northwind.Odata.Api.Client.Models.Order>? Orders { get; set; }
#nullable restore
#else
        public List<global::Northwind.Odata.Api.Client.Models.Order> Orders { get; set; }
#endif
        /// <summary>The photo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public byte[]? Photo { get; set; }
#nullable restore
#else
        public byte[] Photo { get; set; }
#endif
        /// <summary>The photoPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhotoPath { get; set; }
#nullable restore
#else
        public string PhotoPath { get; set; }
#endif
        /// <summary>The postalCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostalCode { get; set; }
#nullable restore
#else
        public string PostalCode { get; set; }
#endif
        /// <summary>The region property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>The reportsTo property</summary>
        public int? ReportsTo { get; set; }
        /// <summary>The reportsToNavigation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Northwind.Odata.Api.Client.Models.Employee? ReportsToNavigation { get; set; }
#nullable restore
#else
        public global::Northwind.Odata.Api.Client.Models.Employee ReportsToNavigation { get; set; }
#endif
        /// <summary>The territories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Northwind.Odata.Api.Client.Models.Territory>? Territories { get; set; }
#nullable restore
#else
        public List<global::Northwind.Odata.Api.Client.Models.Territory> Territories { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The titleOfCourtesy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TitleOfCourtesy { get; set; }
#nullable restore
#else
        public string TitleOfCourtesy { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Northwind.Odata.Api.Client.Models.Employee"/> and sets the default values.
        /// </summary>
        public Employee()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Northwind.Odata.Api.Client.Models.Employee"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Northwind.Odata.Api.Client.Models.Employee CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Northwind.Odata.Api.Client.Models.Employee();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetStringValue(); } },
                { "birthDate", n => { BirthDate = n.GetDateTimeOffsetValue(); } },
                { "city", n => { City = n.GetStringValue(); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "employeeId", n => { EmployeeId = n.GetIntValue(); } },
                { "extension", n => { Extension = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "hireDate", n => { HireDate = n.GetDateTimeOffsetValue(); } },
                { "homePhone", n => { HomePhone = n.GetStringValue(); } },
                { "inverseReportsToNavigation", n => { InverseReportsToNavigation = n.GetCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.Employee>(global::Northwind.Odata.Api.Client.Models.Employee.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "orders", n => { Orders = n.GetCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.Order>(global::Northwind.Odata.Api.Client.Models.Order.CreateFromDiscriminatorValue)?.AsList(); } },
                { "photo", n => { Photo = n.GetByteArrayValue(); } },
                { "photoPath", n => { PhotoPath = n.GetStringValue(); } },
                { "postalCode", n => { PostalCode = n.GetStringValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "reportsTo", n => { ReportsTo = n.GetIntValue(); } },
                { "reportsToNavigation", n => { ReportsToNavigation = n.GetObjectValue<global::Northwind.Odata.Api.Client.Models.Employee>(global::Northwind.Odata.Api.Client.Models.Employee.CreateFromDiscriminatorValue); } },
                { "territories", n => { Territories = n.GetCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.Territory>(global::Northwind.Odata.Api.Client.Models.Territory.CreateFromDiscriminatorValue)?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "titleOfCourtesy", n => { TitleOfCourtesy = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address", Address);
            writer.WriteDateTimeOffsetValue("birthDate", BirthDate);
            writer.WriteStringValue("city", City);
            writer.WriteStringValue("country", Country);
            writer.WriteIntValue("employeeId", EmployeeId);
            writer.WriteStringValue("extension", Extension);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteDateTimeOffsetValue("hireDate", HireDate);
            writer.WriteStringValue("homePhone", HomePhone);
            writer.WriteCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.Employee>("inverseReportsToNavigation", InverseReportsToNavigation);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteStringValue("notes", Notes);
            writer.WriteCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.Order>("orders", Orders);
            writer.WriteByteArrayValue("photo", Photo);
            writer.WriteStringValue("photoPath", PhotoPath);
            writer.WriteStringValue("postalCode", PostalCode);
            writer.WriteStringValue("region", Region);
            writer.WriteIntValue("reportsTo", ReportsTo);
            writer.WriteObjectValue<global::Northwind.Odata.Api.Client.Models.Employee>("reportsToNavigation", ReportsToNavigation);
            writer.WriteCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.Territory>("territories", Territories);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("titleOfCourtesy", TitleOfCourtesy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
