// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Northwind.Odata.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrderDetail : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The discount property</summary>
        public float? Discount { get; set; }
        /// <summary>The order property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Northwind.Odata.Api.Client.Models.Order? Order { get; set; }
#nullable restore
#else
        public global::Northwind.Odata.Api.Client.Models.Order Order { get; set; }
#endif
        /// <summary>The orderId property</summary>
        public int? OrderId { get; set; }
        /// <summary>The product property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Northwind.Odata.Api.Client.Models.Product? Product { get; set; }
#nullable restore
#else
        public global::Northwind.Odata.Api.Client.Models.Product Product { get; set; }
#endif
        /// <summary>The productId property</summary>
        public int? ProductId { get; set; }
        /// <summary>The quantity property</summary>
        public int? Quantity { get; set; }
        /// <summary>The unitPrice property</summary>
        public decimal? UnitPrice { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Northwind.Odata.Api.Client.Models.OrderDetail"/> and sets the default values.
        /// </summary>
        public OrderDetail()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Northwind.Odata.Api.Client.Models.OrderDetail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Northwind.Odata.Api.Client.Models.OrderDetail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Northwind.Odata.Api.Client.Models.OrderDetail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "discount", n => { Discount = n.GetFloatValue(); } },
                { "order", n => { Order = n.GetObjectValue<global::Northwind.Odata.Api.Client.Models.Order>(global::Northwind.Odata.Api.Client.Models.Order.CreateFromDiscriminatorValue); } },
                { "orderId", n => { OrderId = n.GetIntValue(); } },
                { "product", n => { Product = n.GetObjectValue<global::Northwind.Odata.Api.Client.Models.Product>(global::Northwind.Odata.Api.Client.Models.Product.CreateFromDiscriminatorValue); } },
                { "productId", n => { ProductId = n.GetIntValue(); } },
                { "quantity", n => { Quantity = n.GetIntValue(); } },
                { "unitPrice", n => { UnitPrice = n.GetDecimalValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("discount", Discount);
            writer.WriteObjectValue<global::Northwind.Odata.Api.Client.Models.Order>("order", Order);
            writer.WriteIntValue("orderId", OrderId);
            writer.WriteObjectValue<global::Northwind.Odata.Api.Client.Models.Product>("product", Product);
            writer.WriteIntValue("productId", ProductId);
            writer.WriteIntValue("quantity", Quantity);
            writer.WriteDecimalValue("unitPrice", UnitPrice);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
