// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Northwind.Odata.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Order : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The customer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Northwind.Odata.Api.Client.Models.Customer? Customer { get; set; }
#nullable restore
#else
        public global::Northwind.Odata.Api.Client.Models.Customer Customer { get; set; }
#endif
        /// <summary>The customerId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>The employee property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Northwind.Odata.Api.Client.Models.Employee? Employee { get; set; }
#nullable restore
#else
        public global::Northwind.Odata.Api.Client.Models.Employee Employee { get; set; }
#endif
        /// <summary>The employeeId property</summary>
        public int? EmployeeId { get; set; }
        /// <summary>The freight property</summary>
        public decimal? Freight { get; set; }
        /// <summary>The orderDate property</summary>
        public DateTimeOffset? OrderDate { get; set; }
        /// <summary>The orderDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Northwind.Odata.Api.Client.Models.OrderDetail>? OrderDetails { get; set; }
#nullable restore
#else
        public List<global::Northwind.Odata.Api.Client.Models.OrderDetail> OrderDetails { get; set; }
#endif
        /// <summary>The orderId property</summary>
        public int? OrderId { get; set; }
        /// <summary>The requiredDate property</summary>
        public DateTimeOffset? RequiredDate { get; set; }
        /// <summary>The shipAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipAddress { get; set; }
#nullable restore
#else
        public string ShipAddress { get; set; }
#endif
        /// <summary>The shipCity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipCity { get; set; }
#nullable restore
#else
        public string ShipCity { get; set; }
#endif
        /// <summary>The shipCountry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipCountry { get; set; }
#nullable restore
#else
        public string ShipCountry { get; set; }
#endif
        /// <summary>The shipName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipName { get; set; }
#nullable restore
#else
        public string ShipName { get; set; }
#endif
        /// <summary>The shippedDate property</summary>
        public DateTimeOffset? ShippedDate { get; set; }
        /// <summary>The shipPostalCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipPostalCode { get; set; }
#nullable restore
#else
        public string ShipPostalCode { get; set; }
#endif
        /// <summary>The shipRegion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipRegion { get; set; }
#nullable restore
#else
        public string ShipRegion { get; set; }
#endif
        /// <summary>The shipVia property</summary>
        public int? ShipVia { get; set; }
        /// <summary>The shipViaNavigation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Northwind.Odata.Api.Client.Models.Shipper? ShipViaNavigation { get; set; }
#nullable restore
#else
        public global::Northwind.Odata.Api.Client.Models.Shipper ShipViaNavigation { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Northwind.Odata.Api.Client.Models.Order"/> and sets the default values.
        /// </summary>
        public Order()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Northwind.Odata.Api.Client.Models.Order"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Northwind.Odata.Api.Client.Models.Order CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Northwind.Odata.Api.Client.Models.Order();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customer", n => { Customer = n.GetObjectValue<global::Northwind.Odata.Api.Client.Models.Customer>(global::Northwind.Odata.Api.Client.Models.Customer.CreateFromDiscriminatorValue); } },
                { "customerId", n => { CustomerId = n.GetStringValue(); } },
                { "employee", n => { Employee = n.GetObjectValue<global::Northwind.Odata.Api.Client.Models.Employee>(global::Northwind.Odata.Api.Client.Models.Employee.CreateFromDiscriminatorValue); } },
                { "employeeId", n => { EmployeeId = n.GetIntValue(); } },
                { "freight", n => { Freight = n.GetDecimalValue(); } },
                { "orderDate", n => { OrderDate = n.GetDateTimeOffsetValue(); } },
                { "orderDetails", n => { OrderDetails = n.GetCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.OrderDetail>(global::Northwind.Odata.Api.Client.Models.OrderDetail.CreateFromDiscriminatorValue)?.AsList(); } },
                { "orderId", n => { OrderId = n.GetIntValue(); } },
                { "requiredDate", n => { RequiredDate = n.GetDateTimeOffsetValue(); } },
                { "shipAddress", n => { ShipAddress = n.GetStringValue(); } },
                { "shipCity", n => { ShipCity = n.GetStringValue(); } },
                { "shipCountry", n => { ShipCountry = n.GetStringValue(); } },
                { "shipName", n => { ShipName = n.GetStringValue(); } },
                { "shipPostalCode", n => { ShipPostalCode = n.GetStringValue(); } },
                { "shipRegion", n => { ShipRegion = n.GetStringValue(); } },
                { "shipVia", n => { ShipVia = n.GetIntValue(); } },
                { "shipViaNavigation", n => { ShipViaNavigation = n.GetObjectValue<global::Northwind.Odata.Api.Client.Models.Shipper>(global::Northwind.Odata.Api.Client.Models.Shipper.CreateFromDiscriminatorValue); } },
                { "shippedDate", n => { ShippedDate = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Northwind.Odata.Api.Client.Models.Customer>("customer", Customer);
            writer.WriteStringValue("customerId", CustomerId);
            writer.WriteObjectValue<global::Northwind.Odata.Api.Client.Models.Employee>("employee", Employee);
            writer.WriteIntValue("employeeId", EmployeeId);
            writer.WriteDecimalValue("freight", Freight);
            writer.WriteDateTimeOffsetValue("orderDate", OrderDate);
            writer.WriteCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.OrderDetail>("orderDetails", OrderDetails);
            writer.WriteIntValue("orderId", OrderId);
            writer.WriteDateTimeOffsetValue("requiredDate", RequiredDate);
            writer.WriteStringValue("shipAddress", ShipAddress);
            writer.WriteStringValue("shipCity", ShipCity);
            writer.WriteStringValue("shipCountry", ShipCountry);
            writer.WriteStringValue("shipName", ShipName);
            writer.WriteDateTimeOffsetValue("shippedDate", ShippedDate);
            writer.WriteStringValue("shipPostalCode", ShipPostalCode);
            writer.WriteStringValue("shipRegion", ShipRegion);
            writer.WriteIntValue("shipVia", ShipVia);
            writer.WriteObjectValue<global::Northwind.Odata.Api.Client.Models.Shipper>("shipViaNavigation", ShipViaNavigation);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
