// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Northwind.Odata.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Product : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Northwind.Odata.Api.Client.Models.Category? Category { get; set; }
#nullable restore
#else
        public global::Northwind.Odata.Api.Client.Models.Category Category { get; set; }
#endif
        /// <summary>The categoryId property</summary>
        public int? CategoryId { get; set; }
        /// <summary>The discontinued property</summary>
        public bool? Discontinued { get; set; }
        /// <summary>The orderDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Northwind.Odata.Api.Client.Models.OrderDetail>? OrderDetails { get; set; }
#nullable restore
#else
        public List<global::Northwind.Odata.Api.Client.Models.OrderDetail> OrderDetails { get; set; }
#endif
        /// <summary>The productId property</summary>
        public int? ProductId { get; set; }
        /// <summary>The productName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductName { get; set; }
#nullable restore
#else
        public string ProductName { get; set; }
#endif
        /// <summary>The productUniqueId property</summary>
        public Guid? ProductUniqueId { get; set; }
        /// <summary>The productUri property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductUri { get; set; }
#nullable restore
#else
        public string ProductUri { get; set; }
#endif
        /// <summary>The quantityPerUnit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QuantityPerUnit { get; set; }
#nullable restore
#else
        public string QuantityPerUnit { get; set; }
#endif
        /// <summary>The referenceUniqueId property</summary>
        public Guid? ReferenceUniqueId { get; set; }
        /// <summary>The reorderLevel property</summary>
        public int? ReorderLevel { get; set; }
        /// <summary>The supplier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Northwind.Odata.Api.Client.Models.Supplier? Supplier { get; set; }
#nullable restore
#else
        public global::Northwind.Odata.Api.Client.Models.Supplier Supplier { get; set; }
#endif
        /// <summary>The supplierId property</summary>
        public int? SupplierId { get; set; }
        /// <summary>The unitPrice property</summary>
        public decimal? UnitPrice { get; set; }
        /// <summary>The unitsInStock property</summary>
        public int? UnitsInStock { get; set; }
        /// <summary>The unitsOnOrder property</summary>
        public int? UnitsOnOrder { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Northwind.Odata.Api.Client.Models.Product"/> and sets the default values.
        /// </summary>
        public Product()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Northwind.Odata.Api.Client.Models.Product"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Northwind.Odata.Api.Client.Models.Product CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Northwind.Odata.Api.Client.Models.Product();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "category", n => { Category = n.GetObjectValue<global::Northwind.Odata.Api.Client.Models.Category>(global::Northwind.Odata.Api.Client.Models.Category.CreateFromDiscriminatorValue); } },
                { "categoryId", n => { CategoryId = n.GetIntValue(); } },
                { "discontinued", n => { Discontinued = n.GetBoolValue(); } },
                { "orderDetails", n => { OrderDetails = n.GetCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.OrderDetail>(global::Northwind.Odata.Api.Client.Models.OrderDetail.CreateFromDiscriminatorValue)?.AsList(); } },
                { "productId", n => { ProductId = n.GetIntValue(); } },
                { "productName", n => { ProductName = n.GetStringValue(); } },
                { "productUniqueId", n => { ProductUniqueId = n.GetGuidValue(); } },
                { "productUri", n => { ProductUri = n.GetStringValue(); } },
                { "quantityPerUnit", n => { QuantityPerUnit = n.GetStringValue(); } },
                { "referenceUniqueId", n => { ReferenceUniqueId = n.GetGuidValue(); } },
                { "reorderLevel", n => { ReorderLevel = n.GetIntValue(); } },
                { "supplier", n => { Supplier = n.GetObjectValue<global::Northwind.Odata.Api.Client.Models.Supplier>(global::Northwind.Odata.Api.Client.Models.Supplier.CreateFromDiscriminatorValue); } },
                { "supplierId", n => { SupplierId = n.GetIntValue(); } },
                { "unitPrice", n => { UnitPrice = n.GetDecimalValue(); } },
                { "unitsInStock", n => { UnitsInStock = n.GetIntValue(); } },
                { "unitsOnOrder", n => { UnitsOnOrder = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Northwind.Odata.Api.Client.Models.Category>("category", Category);
            writer.WriteIntValue("categoryId", CategoryId);
            writer.WriteBoolValue("discontinued", Discontinued);
            writer.WriteCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.OrderDetail>("orderDetails", OrderDetails);
            writer.WriteIntValue("productId", ProductId);
            writer.WriteStringValue("productName", ProductName);
            writer.WriteGuidValue("productUniqueId", ProductUniqueId);
            writer.WriteStringValue("productUri", ProductUri);
            writer.WriteStringValue("quantityPerUnit", QuantityPerUnit);
            writer.WriteGuidValue("referenceUniqueId", ReferenceUniqueId);
            writer.WriteIntValue("reorderLevel", ReorderLevel);
            writer.WriteObjectValue<global::Northwind.Odata.Api.Client.Models.Supplier>("supplier", Supplier);
            writer.WriteIntValue("supplierId", SupplierId);
            writer.WriteDecimalValue("unitPrice", UnitPrice);
            writer.WriteIntValue("unitsInStock", UnitsInStock);
            writer.WriteIntValue("unitsOnOrder", UnitsOnOrder);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
