// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Northwind.Odata.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Shipper : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The companyName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyName { get; set; }
#nullable restore
#else
        public string CompanyName { get; set; }
#endif
        /// <summary>The orders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Northwind.Odata.Api.Client.Models.Order>? Orders { get; set; }
#nullable restore
#else
        public List<global::Northwind.Odata.Api.Client.Models.Order> Orders { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>The shipperId property</summary>
        public int? ShipperId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Northwind.Odata.Api.Client.Models.Shipper"/> and sets the default values.
        /// </summary>
        public Shipper()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Northwind.Odata.Api.Client.Models.Shipper"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Northwind.Odata.Api.Client.Models.Shipper CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Northwind.Odata.Api.Client.Models.Shipper();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "companyName", n => { CompanyName = n.GetStringValue(); } },
                { "orders", n => { Orders = n.GetCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.Order>(global::Northwind.Odata.Api.Client.Models.Order.CreateFromDiscriminatorValue)?.AsList(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "shipperId", n => { ShipperId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("companyName", CompanyName);
            writer.WriteCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.Order>("orders", Orders);
            writer.WriteStringValue("phone", Phone);
            writer.WriteIntValue("shipperId", ShipperId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
