// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Northwind.Odata.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Territory : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The employees property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Northwind.Odata.Api.Client.Models.Employee>? Employees { get; set; }
#nullable restore
#else
        public List<global::Northwind.Odata.Api.Client.Models.Employee> Employees { get; set; }
#endif
        /// <summary>The region property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Northwind.Odata.Api.Client.Models.Region? Region { get; set; }
#nullable restore
#else
        public global::Northwind.Odata.Api.Client.Models.Region Region { get; set; }
#endif
        /// <summary>The regionId property</summary>
        public int? RegionId { get; set; }
        /// <summary>The territoryDescription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TerritoryDescription { get; set; }
#nullable restore
#else
        public string TerritoryDescription { get; set; }
#endif
        /// <summary>The territoryId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TerritoryId { get; set; }
#nullable restore
#else
        public string TerritoryId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Northwind.Odata.Api.Client.Models.Territory"/> and sets the default values.
        /// </summary>
        public Territory()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Northwind.Odata.Api.Client.Models.Territory"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Northwind.Odata.Api.Client.Models.Territory CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Northwind.Odata.Api.Client.Models.Territory();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "employees", n => { Employees = n.GetCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.Employee>(global::Northwind.Odata.Api.Client.Models.Employee.CreateFromDiscriminatorValue)?.AsList(); } },
                { "region", n => { Region = n.GetObjectValue<global::Northwind.Odata.Api.Client.Models.Region>(global::Northwind.Odata.Api.Client.Models.Region.CreateFromDiscriminatorValue); } },
                { "regionId", n => { RegionId = n.GetIntValue(); } },
                { "territoryDescription", n => { TerritoryDescription = n.GetStringValue(); } },
                { "territoryId", n => { TerritoryId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Northwind.Odata.Api.Client.Models.Employee>("employees", Employees);
            writer.WriteObjectValue<global::Northwind.Odata.Api.Client.Models.Region>("region", Region);
            writer.WriteIntValue("regionId", RegionId);
            writer.WriteStringValue("territoryDescription", TerritoryDescription);
            writer.WriteStringValue("territoryId", TerritoryId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
